# Importing Libraires

In [1]:
import pandas as pd 
import numpy as np
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import classification_report

# Loading datasets

In [58]:
crime = pd.read_csv('train.csv')
crimetest = pd.read_csv('test.csv')
crime
crimetest 

Id                Dates  DayOfWeek PdDistrict  \
0            0  2015-05-10 23:59:00     Sunday    BAYVIEW   
1            1  2015-05-10 23:51:00     Sunday    BAYVIEW   
2            2  2015-05-10 23:50:00     Sunday   NORTHERN   
3            3  2015-05-10 23:45:00     Sunday  INGLESIDE   
4            4  2015-05-10 23:45:00     Sunday  INGLESIDE   
...        ...                  ...        ...        ...   
884257  884257  2003-01-01 00:01:00  Wednesday    MISSION   
884258  884258  2003-01-01 00:01:00  Wednesday   NORTHERN   
884259  884259  2003-01-01 00:01:00  Wednesday  INGLESIDE   
884260  884260  2003-01-01 00:01:00  Wednesday    BAYVIEW   
884261  884261  2003-01-01 00:01:00  Wednesday    TARAVAL   

                            Address           X          Y  
0           2000 Block of THOMAS AV -122.399588  37.735051  
1                3RD ST / REVERE AV -122.391523  37.732432  
2            2000 Block of GOUGH ST -122.426002  37.792212  
3          4700 Block of MISSION ST -122.437394  37.721412  
4          4700 Block of MISSION ST -122.437394  37.721412  
...                             ...         ...        ...  
884257      2600 Block of BRYANT ST -122.408983  37.751987  
884258  1900 Block of WASHINGTON ST -122.425342  37.792681  
884259     5500 Block of MISSION ST -122.445418  37.712075  
884260      1500 Block of HUDSON AV -122.387394  37.739479  
884261       1500 Block of SLOAT BL -122.489714  37.733950  

[884262 rows x 7 columns]

# Data Preporcessing

In [3]:
crime['latlong'] = crime['X']*crime['Y']
crimetest['latlong'] = crime['X']*crime['Y']

In [4]:
crime
crimetest

Id                Dates  DayOfWeek PdDistrict  \
0            0  2015-05-10 23:59:00     Sunday    BAYVIEW   
1            1  2015-05-10 23:51:00     Sunday    BAYVIEW   
2            2  2015-05-10 23:50:00     Sunday   NORTHERN   
3            3  2015-05-10 23:45:00     Sunday  INGLESIDE   
4            4  2015-05-10 23:45:00     Sunday  INGLESIDE   
...        ...                  ...        ...        ...   
884257  884257  2003-01-01 00:01:00  Wednesday    MISSION   
884258  884258  2003-01-01 00:01:00  Wednesday   NORTHERN   
884259  884259  2003-01-01 00:01:00  Wednesday  INGLESIDE   
884260  884260  2003-01-01 00:01:00  Wednesday    BAYVIEW   
884261  884261  2003-01-01 00:01:00  Wednesday    TARAVAL   

                            Address           X          Y      latlong  
0           2000 Block of THOMAS AV -122.399588  37.735051 -4624.588916  
1                3RD ST / REVERE AV -122.391523  37.732432 -4624.588916  
2            2000 Block of GOUGH ST -122.426002  37.792212 -4627.691645  
3          4700 Block of MISSION ST -122.437394  37.721412 -4627.847257  
4          4700 Block of MISSION ST -122.437394  37.721412 -4624.699819  
...                             ...         ...        ...          ...  
884257      2600 Block of BRYANT ST -122.408983  37.751987          NaN  
884258  1900 Block of WASHINGTON ST -122.425342  37.792681          NaN  
884259     5500 Block of MISSION ST -122.445418  37.712075          NaN  
884260      1500 Block of HUDSON AV -122.387394  37.739479          NaN  
884261       1500 Block of SLOAT BL -122.489714  37.733950          NaN  

[884262 rows x 8 columns]

In [5]:
crime.drop(['X','Y','Dates'],axis='columns',inplace=True)
crimetest.drop(['X','Y','Dates','Id'],axis='columns',inplace=True)

In [7]:
crime

Category  Descript  DayOfWeek  PdDistrict  Resolution  Address  \
0             37       866          6           4           0    19790   
1             21       810          6           4           0    19790   
2             21       810          6           4           0    22697   
3             16       404          6           4          11     4266   
4             16       404          6           5          11     1843   
...          ...       ...        ...         ...         ...      ...   
878044        25       661          1           8          11    15816   
878045        16       404          1           2          11    11491   
878046        16       404          1           7          11    11315   
878047        35       496          1           7          11    22308   
878048        12       204          1           0          11     5128   

        latlong  
0         12609  
1         12609  
2          1999  
3          1571  
4         12206  
...         ...  
878044    29874  
878045    25037  
878046    13199  
878047    14848  
878048    28278  

[878049 rows x 7 columns]

# Label Encoding

In [6]:
label_encoder = LabelEncoder()
crime = crime[['Category','Descript','DayOfWeek','PdDistrict','Resolution','Address','latlong']].apply(label_encoder.fit_transform)
crimetest = crimetest[['DayOfWeek','PdDistrict','Address','latlong']].apply(label_encoder.fit_transform)



In [8]:
crimetest

DayOfWeek  PdDistrict  Address  latlong
0               3           0     6407    12609
1               3           0     9744    12609
2               3           4     6336     1999
3               3           2    10633     1571
4               3           2    10633    12206
...           ...         ...      ...      ...
884257          6           3     7663    34243
884258          6           4     5411    34243
884259          6           2    11240    34243
884260          6           0     4231    34243
884261          6           8     4313    34243

[884262 rows x 4 columns]

# Explotary Data Analysis(EDA)

In [27]:
x=crime[['Category','Descript','DayOfWeek','PdDistrict','Address','latlong']]
y=crime['Resolution']

In [56]:
x2_test=crimetest[['DayOfWeek','PdDistrict','Address','latlong']]

# Data Spliting for Training & Testing

In [36]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.1,random_state=42)


# Naive Bayes (MultinomialNB) Models Training

In [29]:
nav = MultinomialNB()

In [30]:
nav.fit(x,y)

MultinomialNB()

In [44]:
nav.score(x,y)

0.07451406470481715

In [45]:
nav_pred =nav.predict(x_test)
nav_pred

array([10,  1,  1, ..., 10,  1, 10])

In [55]:
print(classification_report(nav_pred,y_test))

              precision    recall  f1-score   support

           0       0.04      0.27      0.07      2957
           1       0.52      0.10      0.17     39292
           2       0.05      0.00      0.00       668
           3       0.02      0.01      0.01       825
           4       0.00      0.00      0.00       488
           5       0.00      0.00      0.00       651
           6       0.00      0.00      0.00       159
           7       0.01      0.01      0.01       800
           8       0.02      0.01      0.01      1057
           9       0.04      0.00      0.00      3343
          10       0.55      0.03      0.06     29994
          11       0.01      0.60      0.02       834
          12       0.03      0.01      0.01      2211
          13       0.01      0.01      0.01       302
          14       0.14      0.00      0.00      2150
          15       0.18      0.13      0.15      2034
          16       0.00      0.00      0.00        40

    accuracy              

# KNN Models Training 

In [32]:
knn = KNeighborsClassifier(n_neighbors=1)

In [33]:
knn.fit(x,y)

KNeighborsClassifier(n_neighbors=1)

In [34]:
knn.score(x,y)

C:\Users\Hiten\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


0.9378360433187669

In [41]:
knn_pred =knn.predict(x_test)
knn_pred

C:\Users\Hiten\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([11,  0,  0, ...,  4, 11,  0])

In [42]:
print(classification_report(knn_pred,y_test))

              precision    recall  f1-score   support

           0       0.93      0.92      0.92     20986
           1       0.85      0.91      0.88      7247
           2       0.71      0.65      0.68        23
           3       0.87      0.89      0.88       374
           4       0.88      0.90      0.89       376
           5       0.83      0.85      0.84       140
           6       0.71      0.77      0.74       142
           7       0.82      0.78      0.80       597
           8       0.76      0.75      0.76       358
           9       0.82      0.82      0.82        28
          10       0.77      0.85      0.81      1543
          11       0.97      0.96      0.96     53054
          12       0.79      0.89      0.84       327
          13       0.90      0.94      0.92       233
          14       0.71      0.83      0.77         6
          15       0.86      0.87      0.86      1459
          16       0.85      0.89      0.87       912

    accuracy              

# Regression (Logistic) Models Training

In [47]:
reg = LogisticRegression()


In [48]:
reg.fit(x,y)

C:\Users\Hiten\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [51]:
reg.score(x,y)

0.5968755730033289

In [53]:
reg_pred =reg.predict(x_test)
reg_pred

array([11, 11, 11, ..., 11, 11, 11])

In [54]:
print(classification_report(reg_pred,y_test))

              precision    recall  f1-score   support

           0       0.00      0.15      0.00       325
           1       0.00      0.01      0.00       132
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0
           4       0.00      0.00      0.00         0
           5       0.00      0.00      0.00         0
           6       0.00      0.00      0.00         0
           7       0.00      0.00      0.00         0
           8       0.00      0.00      0.00         0
           9       0.00      0.00      0.00         0
          10       0.00      0.00      0.00         0
          11       0.99      0.60      0.75     87348
          12       0.00      0.00      0.00         0
          13       0.00      0.00      0.00         0
          14       0.00      0.00      0.00         0
          15       0.00      0.00      0.00         0
          16       0.00      0.00      0.00         0

    accuracy              

C:\Users\Hiten\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Hiten\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Hiten\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
